
raman_repetition_rate = 504803673.9494223
rabi_to_voltage = 1e3
max_ions = 4

[doppler_cooling]
duration = 10000

[rsb_cooling]
duration = 1000

[optical_pumping]
duration = 2000

[raman1]
raw_frequency = 5306061493668561.0
transition = "q1->e1m"

[raman2]
raw_frequency = 5306142187360824.0
transition = "q0->e1m"

[detection]
transition = "q1->e0"
detection_beam_channel = 4
detector_channel = 5

[artiq]
initial_slack = 100000
machine_unit = 1e-9

[spectrum_awg]
trigger_time = 200
response_time = 512

[aod]
max_cores = 20
frequency_separation = 1e5

[urukul0]
set_time = 8000
response_time = 0

[urukul1]
set_time = 8000
response_time = 0
