
raman_repetition_rate = 504803673.9494223
rabi_to_voltage = 1e3
max_ions = 4


[raman1]
raw_frequency = 5306062624641916.0
transition = "upstate->estate"

[raman2]
raw_frequency = 5306142187360824.0
transition = "downstate->estate"

[detection]
transition = "upstate->estate2"
detection_beam_channel = 4
detector_channel = 5
downstate_exp_lambda_per_us = 0.25
upstate_poisson_lambda_per_us = 1
transfer_time = 10000
ttlout_init_time = 10
ttlout_time = 50
ttlout_gap_time = 200


[artiq]
initial_slack = 10000
machine_unit = 1e-9

[spectrum_awg]
trigger_time = 200
response_time = 512

[aod]
max_cores = 20
frequency_separation = 5e4

[urukul0]
set_time = 8000
response_time = 0

[urukul1]
set_time = 8000
response_time = 0
